project:
  type: website
  output-dir: docs

website:
  navbar:
    left:
      - href: SINASC.qmd
        text: Home
      - href: fatores.qmd
        text: Descriptive Analysis

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

